#ifndef CANFTP_SERVER_SESSION_PARAMS_H_
#define CANFTP_SERVER_SESSION_PARAMS_H_

//
#define CANFTP_SERVER_SESSION_REGISTRATION_INTERVAL 100
//
#define CANFTP_SERVER_SESSION_REGISTRATION_COUNT 10
//
#define CANFTP_SERVER_SESSION_SESSIONCONTROL_INTERVAL 100
//
#define CANFTP_SERVER_SESSION_SESSIONCONTROL_COUNT 10
//
#define CANFTP_SERVER_SESSION_BLOCKREPEATE_COUNT 10
//
#define CANFTP_SERVER_SESSION_BLCOCKCONTROL_INTERVAL 100
//
#define CANFTP_SERVER_SESSION_BLOCKCONTROL_COUNT 10
//
#define CANFTP_SERVER_SESSION_FRAMESENDING_INTERVAL 1
//
#define CANFTP_SERVER_SESSION_ACKREPEATE_INTERVAL 100
//
#define CANFTP_SERVER_SESSION_ACKREPEATE_COUNT 10
//
#define CANFTP_SERVER_SESSION_LOSTCONNECTION_TIMEOUT 10000

#endif // CANFTP_SERVER_SESSION_PARAMS_H_
