#ifndef CANFTP_ERRORTYPE_H_
#define CANFTP_ERRORTYPE_H_

/*
    Тип ошибки
*/
typedef enum _CanFTP_ErrorType
{
    CANFTP_ERROR_LIST_OUTOFEANGE = 1,
    CANFTP_ERROR_LIST_STRANGERELEMENT = 2,
    CANFTP_ERROR_TIME_NOTTIMEGETTER = 3,
    CANFTP_ERROR_TIME_TIMEMARK = 4,
    CANFTP_ERROR_CLIENT_NULL = 5,
    CANFTP_ERROR_FMS_NOBODYHANLER = 5,
    CANFTP_ERROR_FMS_OUTOFHANDLERS = 6,
    CANFTP_ERROR_MESSAGES_WRONGTYPE = 7,
    CANFTP_ERROR_MESSAGES_WRONGPARAMS = 8,
    CANFTP_ERROR_CLIENTSCOLLECTION_OUTOFEANGE = 9,
    CANFTP_ERROR_SESSIONSCOLLECTION_OUTOFEANGE = 10,
    CANFTP_ERROR_SERVER_NULL = 11,
    CANFTP_ERROR_SESSION_BLOCKERROR = 12,
    CANFTP_ERROR_CLIENT_ALREADYINSESSION = 13,
    CANFTP_ERROR_SESSION_NULL = 14,
    CANFTP_ERROR_FILEBLOCK_OUTOFEANGE = 15,

} CanFTP_ErrorType_t;

#endif // CANFTP_ERRORTYPE_H_
